### ISSUE TITLE
Order form details not getting passed to Member dashboard

### ISSUE THREAD

**Issue by OgheneTega** [strangerstudios/paystack-gateway-paid-memberships-pro#9]
Hello team,

Additionally, we've received reports indicating that order details created to capture user information are not being returned after payment. For example, if a merchant has created extra form fields to capture user details, these fields are not being populated with the data entered by the user at the point of sign-up, as shown in the attached images.

Let me know if I can help with anything. Thank you

<img width="115" alt="image001" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/26255092/552f12be-7c93-4340-a7c4-26680b509a16">
<img width="115" alt="image002" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/26255092/400758f9-1841-4bea-8922-6ae6b3f443db">
<img width="115" alt="image003" src="https://github.com/strangerstudios/paystack-gateway-paid-memberships-pro/assets/26255092/eb59dc09-738d-4d27-a035-e4d0b7c896a5">

**Comment by andrewlimaza** [comment]
@OgheneTega Thanks for reaching out to us here. I will need a bit more information to try and replicate and debug this:

* What version of this plugin are you using as this should have been fixed in a recent release.
* Can you confirm that the orders are completed successfully?
* How are these fields created using User Fields (https://www.paidmembershipspro.com/documentation/user-fields/) or with another plugin like ACF/Pods?

**Comment by OgheneTega** [comment]
Hi @andrewlimaza,

My apologies for not responding earlier. I can confirm that this has been fixed.

My initial test was with version 1.7.2 and I recently got to test with version 1.7.5, created the fields using user fields and after the order was completed, I could see the extra information on the member page.

Thank you very much for your assistance.

**Comment by andrewlimaza** [comment]
Awesome thanks for letting me know! I will close this issue and mark it as resolved.
